### ISSUE TITLE
Proposal for go-app v10 - Your Suggestions and Deprecations Input

### ISSUE THREAD

**Issue by maxence-charriere** [maxence-charriere/go-app#875]
Hello go-app community,

I hope you're all doing well. As I start working on the next major version of go-app (v10), I want to involve you in the decision-making process by inviting your suggestions and thoughts on new features and potential changes.

## What I'm Seeking

I truly value your insights. If you've been holding onto ideas or have suggestions to improve go-app, now is the perfect time to share them. Please take a moment to comment below with your thoughts on what you'd like to see in v10.

## Proposed Changes

For this upcoming version, I have a couple of modifications in mind that I'd like to discuss with you:

1. **Deprecation of `app.If(v bool, v ...app.UI)` Call**:
   Currently, the `app.If(v boo, v ...app.UIl)` call generates unnecessary memory allocations. To address this, I'm considering replacing it with `app.If(v bool, func() app.UI)`. My goal is to retain the familiar code semantics while boosting efficiency. I'm eager to know your perspective on this change and whether it aligns with your needs.

2. **Transition of String Argument Functions to Format Version, Including `app.Text` and Other `Text` Methods**:
   Another proposal is to transition functions that currently take a string argument to a format version. This would encompass methods like `app.Text`. The adjusted function signature would be something like `func(format string, v ...any)`. Initially, I plan to use `fmt.Sprintf`, but my ultimate aim is to introduce a more optimized function for the same results. Your insights on this transition would be incredibly valuable.

3. **Replacement of `app.Route(path string, v app.Compo)` Functions with Factory Function `app.Route(path string, func app.UI)`, Removing Duplicates**:
   The usage of `app.Route(path string, v app.Compo)` functions has raised confusion among many users. In order to streamline and enhance clarity, I'm considering a replacement that involves taking a factory function as an argument, something like `app.Route(path string, func app.UI)`. This adjustment aims to simplify the process and improve usability while ensuring a consistent approach across routes. As part of this transition, duplicates such as `app.RouteFunc(path string)` will be removed to maintain a clean and efficient API. Your thoughts on this transition are greatly appreciated.

4. **Uniformization and Simplification of `app.Handler` Syntax**:
   The evolution of `app.Handler` has led to a growing complexity in both syntax and underlying mechanisms. To achieve API uniformity and simplify this aspect of go-app, I'm contemplating adopting a syntax similar to components. This change aims to enhance consistency while providing a more straightforward approach to using `app.Handler`.

5. **Documentation Relocation**:
   The influx of documentation-related requests has introduced noise to this repository. To address this and ensure a cleaner environment for issue discussions, I'm considering moving the documentation to a separate repository or adopting a GitHub Wiki-like approach. This change aims to improve the user experience and keep our discussions focused on enhancements and issues.

## Your Voice Matters

Your feedback drives the direction of go-app. Please share your thoughts on these proposed changes, offer your opinions, and suggest any alternative ideas you might have.

Thank you for being an integral part of the go-app community. Your contributions and insights fuel our progress. Let's collaborate to make v10 the most remarkable version yet!

I'm eagerly looking forward to hearing from you.

Warm regards,
Maxence

**Comment by oderwat** [comment]
Hey Maxence,

here are my views:

1. It is obvious, that I do not like the current `If()`. I also think it is not just about allocations, but about code that may get executed "for nothing".
  BTW: "Deprecation of `app.If(v bool)` Call" should probably "Deprecation of app.If(v bool, elems ...UI) Call" in your text. I was initially irritated that there is a "preparation" if. Which could mean something like `app.If(condition).Then(func()).Else(func()).EndIf()`
2. I do not like having "Text()" using a format string because you need to guard it behind the `varargs count` or end up with format specifiers not printed correctly (escaping them would be a horror). I think I prefer having `Text(string)`, `Textf(format, args)` without any magic. I may like having "Text(... string)" instead and had it concatenate the texts using a string builder or just `strings.Join()`. For `fmt.Sprintf()` I wonder if you can do better than the standard library and still support everything possible.
3. Yes, but I still think that some comments and more examples would make this clear enough for the current release too.
4. I would need to see some example code. I have no problem with the current implementation, though.
5. The reasoning is not clear to me. Just tagging issues would make clear what is just about documentation, and users will probably still mix all of it inside this repository. You then need to ask them to go somewhere else, and if you will introduce even more noise. I think "go-app.dev" is not an ideal way for documentation either (I understand that it is a showcase for Go-App, but then it should do some more stuff, like Search/Commenting and so on). I also have yet to experience a good working "GitHub wiki". I may be wrong, but usually the wiki is not really "maintained" and stuff ends up mixed all over the place. Likewise, I think a good way of documentation are additional README's inside the repository at package level or an example hierarchy, and of course, Go docs. This lets people hand you PR's for extra documentation and more examples. Like for example [here](https://github.com/nats-io/nats.go/tree/main/jetstream).

I have another change that I would like: Ignore nil arguments in `Body()` `app.Div().Body(c.header(),c.updateInfo(),c.content(),c.footer())` would then ignore if `c.updateInfo()` returned nil. Currently, I have to build a slice beforehand.

I actually do not even think that most of my wishes need another major release.

**Comment by maxence-charriere** [comment]
Hey @oderwat, thanks for the answer.
I ll take time to answer this with more details, just a note that every Body methods use FilterUIElems which already ignore nil values.

**Comment by oderwat** [comment]
> FilterUIElems which already ignore nil values

I have to re-check. I thought I got errors with that.

**Comment by maxence-charriere** [comment]
> I do not like having "Text()" using a format string because you need to guard it behind the varargs count or end up with format specifiers not printed correctly (escaping them would be a horror). I think I prefer having Text(string), Textf(format, args) without any magic. I may like having "Text(... string)" instead and had it concatenate the texts using a string builder or just strings.Join(). For fmt.Sprintf() I wonder if you can do better than the standard library and still support everything possible.

Thank you for sharing your insights.

I understand the concern. For context, in my codebase for [Murlok.io](https://Murlok.io), a significant portion of the string arguments are formatted with `fmt.Sprintf`. I've noticed that this tends to clutter the code and hampers readability.

There are hundreds of calls in the current setup that could benefit from format args. Introducing an `F` version for all these calls, such as `Text(string)` and `Textf(string, ...any)`, would substantially increase the call stack. From a design perspective, it could introduce redundancy and potentially complicate function names. I believe standardizing to format args provides a more streamlined approach.

It's important to note that having a format string by default doesn't prevent the usage of the first argument as a non-format string. For instance, you can still perform concatenations like `"str1" + "str2"`.

Additionally, the present implementation of `Text(v any)` employs various methods to format the argument, with `fmt.Sprintf("%v")` being the default fallback. This kind of forces a format onto the user, which isn't always desirable.

**Comment by oderwat** [comment]
@maxence-charriere I am fine without the "magic" and add my `fmt.Sprintf()` or a shorter stub version for that. Curious about me having no "bad memories" I did a quick check with the currently largest "little" project and found 4 `Sprintf()` in the roughly 5000 lines of code that is the PWA components. There is only one used with `.Text()` while the others are actually unrelated. But I also have only 56 calls to `Text()` overall.

> it's important to note that having a format string by default doesn't prevent the usage of the first argument as a non-format string. For instance, you can still perform concatenations like "str1" + "str2".

But this is only possible if your check is there is more than one argument in the call, and all of my code will run slower. 

I also do not know if it actually changes the code the compiler produces with functions that accept variable arguments. I read some (old?) information that it has to be allocated to the heap, and even if not, it should take up space and make everything slower for those that do not want or need to use the format string. I did some quick and lazy experiments, and it seems at least to allocate the only/first variable in different memory regions. But even with `//go:noinline pragma` it was not a big difference in speed. But I would actually suggest that you do some kind of benchmark to see what happens. Especially, having a lot more GC activity would be awful for the frontend in the browser. It should be possible to check the WASM disassembly for the code. If one cares.

**Comment by mlctrez** [comment]
Hey Maxence,

My thoughts:
1. Same as @oderwat on this one. 
2. I would lean towards keeping the default `.Text(v any)` method and only add `.Textf(format string, a ...any)` as in the v9.8.0 [release](https://github.com/maxence-charriere/go-app/blob/11db7b1782f093cd86cc7fe2de63c70b8b01b877/pkg/app/text.go#L18).
2a. You mention *other `Text` methods* - would this be more than what's in the v9.8.0 release?
3. Same as @oderwat on this one. 
4. Same as @oderwat on this one.  
4a. I do see a point that providing app.Handler defaults is problematic with the current code base. I would also be interested in seeing what a new implementation looks like.
5. I can see your point with the recent PRs being opened in the main repo a desire to move that documentation elsewhere. I also agree with @oderwat that user's are going to open PRs on the main repo even if there is another one that is more appropriate for `how do I do this` questions.
5a. I would lean toward refreshing [go-app-demo](https://github.com/maxence-charriere/go-app-demo/) to the current release and provide enough examples there. I believe this would cut down quite a bit on the `does not work as expected` PRs.  Also, configuring some [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) could help in getting valid bug/feature enhancements for the main repo. With 90+ issues open on the main repo, it might be a good idea to setup automatic closing on those that are just hanging out there with no activity. 

As @oderwat mentioned, I don't see any of these changes resulting in a new major version ( with the exception of 4 if the api changes quite a bit ).

Matt

**Comment by maxence-charriere** [comment]
The proposed changes to `If` will break compatibility on their own. I'll provide an update later regarding the adjustments to `app.Handler`.

**Regarding the documentation**, I'd like to clarify a few points:
- The current documentation consists of the Go-generated references alongside the markdown files. 
- It's important to me that we retain these markdown files within the `go-app` repository.

Additionally, I've been contemplating a project for some time that essentially replicates what the current documentation website does but makes it accessible for wider community use. Consequently, any issues related to documentation in this repository will be primarily centered on content.

**Comment by rtrzebinski** [comment]
I'd love the option to inject dependencies when defining app.Routes, for instance:

```
app.Route(components.PathHome, &components.Home{})
```

Could have a dependency injected like this:

```
app.Route(components.PathHome, &components.Home{service})
```

Currently it always lands as an empty struct.

**Comment by maxence-charriere** [comment]
Hello everyone,

I've dedicated significant effort towards refining v10 recently, particularly focusing on the refactoring of the engine code. Here are the key updates:

- **Deprecation of `OnInit` within the `Initializer` interface**: The primary function of `OnInit` was to facilitate initialization prior to the first-time rendering of a component. Given that `OnMount` now also triggers right before the first rendering of the component, the `Initializer` interface has become obsolete.
  
- **Deprecation of `PreRenderer` interface**: After working with it for some time, I've found it to be an overly complex segment of the codebase. This has now been removed. For specific tuning regarding where code is executed, simply use `if app.IsServer` or `if app.IsClient`.
  
- **Modification to `Context.ObserveState`**: It now requires the receiver as its second argument, leading to the removal of the observer's Value method.
  
- **Updates to `Context.SetState`**: It no longer accommodates options. Instead, it now returns a State object that includes methods to persist, set a timeout for, and broadcast the state. This modification was intended to enhance the discoverability of options. For instance: `ctx.SetState("test", 42).Persist()`.

Your feedback would be invaluable. Feel free to check out and try these changes on https://github.com/maxence-charriere/go-app/tree/node-manager

**Comment by maxence-charriere** [comment]
@rtrzebinski https://github.com/maxence-charriere/go-app/issues/875#issuecomment-1712422429
This is feasible since Handle now takes a function that creates a component.

**Comment by oderwat** [comment]
@maxence-charriere LGTM. We are in the middle of a large project, so I do not have too much time at hand. But I will try to get the branch running on the new version. Do you have some ETA for when v10 could be released?

**Comment by maxence-charriere** [comment]
I estimate it will take another month or two. Currently, Murlok.io is utilizing it, but my priority is to ensure that it introduces a minimal number of breaking changes for users like you. I believe the work on the engine is nearing completion. Additionally, I'm looking into reworking the HTTP handler and will also be reviewing and potentially integrating some of the pending PRs.

**Comment by mlctrez** [comment]
@maxence-charriere  I'm testing this out now on a fairly large project and a go-app library used by that project.  

Migration to the new observe state code is trivial so far and improves readability. :+1: 

I'm stuck on how to trigger component updates since this method was removed:

https://github.com/maxence-charriere/go-app/blob/4af747695016174dfbe4502d0754da7ea1b4807b/pkg/app/component.go#L197-L202

I see the new update manager in the V10 code and how it is used internally.
https://github.com/maxence-charriere/go-app/blob/19e43535d3d79c5ca5ed51acae14e04053e4f68a/pkg/app/update.go#L3-L8

What would be the correct way to trigger an update in V10?


Thanks!

**Comment by oderwat** [comment]
@maxence-charriere We also do a lot of out of event handler component updates (like consumers that receive messages from NATS). I also still need the `preventUpdate()` because we do debounce a lot of events. I did not check your new code at all (busy with writing python code PTs for memGPT lol).

**Comment by mlctrez** [comment]
@oderwat 

PreventUpdate is still there, just changed a bit to use the new update manager
https://github.com/maxence-charriere/go-app/blob/b060dac2385d6f31fcd4727dc5956fdc76394056/pkg/app/context.go#L224-L228

**Comment by mlctrez** [comment]
@maxence-charriere    The lastURLVisited lines in `addHistory` and `replaceHistory` in `pkg/app/js_wasm.go` might have been missed during refactoring.  It looks like the engine code handles tracking the last url now.

https://github.com/maxence-charriere/go-app/blob/3d07156e4ca9de2ce9e89e472b804667f3dedf10/pkg/app/js_wasm.go#L274-L286

**Comment by mlctrez** [comment]
Before refactoring, I missed that `OnMount` is now called on server side renders.

> Given that `OnMount` now also triggers right before the first rendering of the component, the Initializer interface has become obsolete.

> For specific tuning regarding where code is executed, simply use if app.IsServer or if app.IsClient.

So to upgrade from V9 -> V10, existing code will need to implement the guard you mentioned in any `OnMount`:

```go
func (a *Audio) OnMount(ctx app.Context) {
	if app.IsServer {
		return
	}
	// existing V9 component mounted code
}
```

I refactored my app and go-app library to add the guard conditions in `OnMount`. When rendering server side html, the client only OnMount code is skipped.

However, the behavior of `JSValue()` appears to be broken in V10. 
When running on the client in V9, `JSValue()` returned the JavaScript value of the dom element. 
With V10 this appears to only return `nil`. 

I tracked it down to the `Compo.rootElement` being nil when `OnMount` is invoked.

https://github.com/maxence-charriere/go-app/blob/d8cf3a592f7cfa5d3781f81d4e6f3eff8f7d06e8/pkg/app/component.go#L155-L160




`OnMount` is called on line 232:
https://github.com/maxence-charriere/go-app/blob/e89c91b09ea23837105cf99a1a291c455c19712b/pkg/app/node.go#L231-L233

But `Compo.rootElement` is not set until line 249:
https://github.com/maxence-charriere/go-app/blob/e89c91b09ea23837105cf99a1a291c455c19712b/pkg/app/node.go#L248-L250

This might be as simple as moving the setRoot up a dozen or so lines, but I don't know the implications of this.

**Comment by maxence-charriere** [comment]
> https://github.com/maxence-charriere/go-app/issues/875#issuecomment-1788156864

The primary purpose of this is to determine whether it's a fragment navigation and to avoid unnecessary page re-renders. This behavior has been in place since before, as seen here => https://github.com/maxence-charriere/go-app/blob/master/pkg/app/app.go#L311.

> https://github.com/maxence-charriere/go-app/issues/875#issuecomment-1788360890

Thank you for pointing this out. The current design results in `OnMount` being called before the js value is set. As a result, one would need to either defer or dispatch to access the js value. I'm debating whether it's better to keep it this way (and document the behavior) or revert to the previous `OnInit` setup. What do you think?

**Comment by oderwat** [comment]
> revert to the previous OnInit setup

I think that is better. We need "OnInit" to run once while mount/dismount components multiple times. I also do not want to have every OnMount needing to check it runs on the server. 

For us, it was all fine as it was before. Using preRender for what the bots see, OnInit to set stuff up before Render is called for the first time. OnMount to attach stuff to the node.

Why are you changing these things? What is the advantage over how it worked before? To me, it looks a bit like changing stuff, for the purpose of changing stuff and then we have to refactor everything until it works as it worked before the changes.

**Comment by maxence-charriere** [comment]
Regarding pre-rendering, I noticed that my codebase started to accumulate duplicate calls. It became apparent that both the server and client often require the same calls, and using `IsServer` or `IsClient` makes it clearer where specific actions take place, enhancing code readability.

As for `OnInit`, I'm contemplating reverting to its original behavior over the new `OnMount`. The goal isn't change for change's sake, but rather to simplify the API and minimize the number of operations involved. The `OnInit` approach seems to offer a clearer and more streamlined interface.

**Comment by mlctrez** [comment]
https://github.com/maxence-charriere/go-app/issues/875#issuecomment-1789767966
>  The primary purpose of this is to determine whether it's a fragment navigation and to avoid unnecessary page re-renders.

Sorry, I was not clear on what I was trying to convey here.  

The wasm build fails to compile because `lastURLVisited` is undefined.  

In the V10 branch, this variable block was removed ( code below is from V9 )
https://github.com/maxence-charriere/go-app/blob/4af747695016174dfbe4502d0754da7ea1b4807b/pkg/app/app.go#L40-L46

**Comment by oderwat** [comment]
As we do not even have the same code for front-end routes and back end routes. So I guess it would never call our front-end OnMount() on the server. I guess we are looking at two complete different use cases.

As `OnInit()` originally was a PR by me, I wanted it for a reason and that is still the case. As usual, I think that the documentation needs to be more clear about what is actually happening. I tell my coders that it is always: `OnInit (called once) -> Render() -> OnMount() (called again after dismount) -> Render()` and that Render has no context and should not change the model. With that we usually get this out of the way very quickly.

**Comment by maxence-charriere** [comment]
I put back OnPreRender and OnInit. @mlctrez can you check if everything works?

**Comment by mlctrez** [comment]
I reverted the conditional `if app.IsServer` checks in `OnMount` and everything works in my app and library. 

There is some delay being introduced in an `OnClick` on one of the UI elements occasionally.  I need to see if that is something that was a V9 -> V10 change or something in my app or environment.

My app and library ( and other go-app source that I've written ) does not make much use of `OnPreRender` and `OnInit` so I'm afraid I don't have much to test with there.

**Comment by maxence-charriere** [comment]
I've implemented several updates on the [v10 branch](https://github.com/maxence-charriere/go-app/tree/v10).

Here's a summary of the latest changes:
- Removed the testing dispatchers. The `NewTestEngine()` function has been introduced as a replacement for the previous testing dispatchers.

@mlctrez, I've made some adjustments regarding the delay issue you mentioned. Could you please give it another try and let me know how it goes?

**Comment by mlctrez** [comment]
@maxence-charriere  I tested again against the new V10 branch and the delay is still present. 

I'll look into the nats.io source code some more and see if I can track down how it is uses goroutines, selects, channels, etc.   What I suspect is happening is that there is contention for the JS UI thread between go-app and the nats.io code.  

The nats.io code is communicating using a web socket and the delay that I'm seeing when clicking on a component ends exactly when pings are sent across the web socket.

**Comment by oderwat** [comment]
@mlctrez we start all NATS consumers in their own go routines, and we also use debouncer code (which also makes them async) for most event handlers.

@maxence-charriere I sadly still can't test the new go-app code as we are short before releasing our biggest go-app application into the beta-tester hell. So far it all worked out quite good. I guess we can check what happens to our code at the end of November.

**Comment by mlctrez** [comment]
@maxence-charriere  I finally found what was different between V9 and V10 that caused my UI delay.  

In V10, the frames ticker is reset to 1 Hour when the ticker fires.

https://github.com/maxence-charriere/go-app/blob/8e43917a3e2a0cd6cf585090d6565f8b362f5a5d/pkg/app/engine.go#L250-L255

In V9, the frames timer is doubled each time the dispatch length is 0 and the ticker fires:

https://github.com/maxence-charriere/go-app/blob/4af747695016174dfbe4502d0754da7ea1b4807b/pkg/app/engine.go#L341-L350

I think that my code was somehow dependent on the frames code being executed more frequently.

Again, I don't think this is something that should be changed for V10, since it is probably a rare case and adding a `ctx.Async()` in the right location solves the delay issue.  My code makes use of actions, state, and websockets, so there still may be something there and if it pops up again I'll let you know.

**Comment by oderwat** [comment]
Some things I would like to see in go-app:

1. We implemented "online/offline" handler callbacks and wondered if this would not be a nice addition for go-app itself.
2. I would love to be able to trigger an update check for the serviceworker through the app. This way one could save one reload when trying to force an update. Currently the serviceworker needs to get installed and then a reload is needed. But to force the app to check for an update you need to reload it beforehand. So you into the same app, then reload into the new app. If one could send a message to the app that there is a new version in another channel (trivial for us having a websocket open) on could tell the webworker to search for and update and it would load that and trigger the normal updater. Hence you only get one reload. This way one can leave the automatic check disabled or have it very slow.
3. Having "OnUpdate" work as I thought it would work. I once tried to actually get to know if the dom is getting updated and thought an "OnUpdate" Handler would be called after a components DOM is getting updated (or before?). But I did not get any calls to that Handler?
4. An official way to queue something as Dispatch() without having a context. Currently we store the context of in "OnMount()" to the component and use that one to call Dispatch() from random Go routines. It seems to work but I have a bad feeling about that for some time. Is this actually supported and if not, what are alternatives. I try to avoid any "state handler" and prefer callbacks for examples.
5. Making the state handlers typesave (using generics / ascii85 + gob encoder instead of json?)
6. Some kind of panic recovery. Currently a panic seems to stop everything including the service worker (right?). It seems that because of that there will never be an check for an update until you can initiate a reload of the app, which is not easy to do when the app is installed and the user is "joe random", We currently add "recover()" into all major async routines like the nats consumers or time loops. Maybe there could be a "recover()" in "engine.start()" that can for example restart the app(?) and set a flag in "app.Paniked" (or whatever) to indicate that the app crashed and was recovered?
7. A official way to extend the service worker (I think we had this somewhere before).

**Comment by maxence-charriere** [comment]
@oderwat 

> 1. We implemented "online/offline" handler callbacks and wondered if this would not be a nice addition for go-app itself.

That's an interesting feature. Could you share more details on how you've implemented this? Understanding your approach would help evaluate its potential integration into go-app.

> 2

This kind of forces how app updates are handled.  Currently, you can use the `AppUpdater` interface for detecting app updates. Broadcasting a state and listening to it across all tabs could be a way to manage this behavior.

> 3 

Here is the updated documentation:
```go
// Updater encapsulates components that require specific behaviors or reactions
// when one of their exported fields is updated by the closest parent component.
// Implementing the Updater interface allows components to define responsive
// actions that should be executed whenever they are modified by a parent.
type Updater interface {
	// OnUpdate is triggered whenever an exported field of the component gets
	// modified by its immediate parent component. This method is an opportunity
	// to handle related reactions or recalculations.
	// This function always runs within the UI goroutine context.
	OnUpdate(Context)
}
```

> 4

The dispatch mechanism includes a safeguard against inappropriate usage, such as within the `Render` method. You could ensure consistent dispatching by setting up your operations at a global level using app.Handle, in which the context is linked to the body element and remains mounted.

> 5 

Regarding not fully switching to generic types, the main concern is the added size to the wasm binary. Could you elaborate on the specific benefits you see in using ascii85 over JSON?

> 6 

There's a panic recovery mechanism in app.go, but it doesn't seem to catch JavaScript errors. Here's the relevant code snippet:
```go
func RunWhenOnBrowser() {
	if IsServer {
		return
	}

	defer func() {
		err := recover()
		displayLoadError(err)
		panic(err)
	}()```


> 7
I haven't removed the service worker template customization. Here's the relevant section:
```go
	// The template used to generate app-worker.js. The template follows the
	// text/template package model.
	//
	// By default set to DefaultAppWorkerJS, changing the template have very
	// high chances to mess up go-app usage. Any issue related to a custom app
	// worker template is not supported and will be closed.
	ServiceWorkerTemplate string
```

If there's anything specific you're looking for or improvements you have in mind, I'd be glad to discuss it further.

**Comment by mlctrez** [comment]
For number 2 from the @oderwat like to haves:

> I would love to be able to trigger an update check for the service worker through the app.

I like this Idea and have come across a few cases where triggering the service worker registration update would be convenient.

Adding this code to `app.js`:
```go
function goappRegistrationUpdate() {
  if (goappServiceWorkerRegistration) {  
    goappServiceWorkerRegistration.update();
  }
}
```
and then being able to call it from go-app:
```go

app.Window().Call("goappRegistrationUpdate")

// or better, hiding the app.Window().Call(...)
app.RegistrationUpdate()

```

**Comment by maxence-charriere** [comment]
What would be the use case? How would you use it?

**Comment by mlctrez** [comment]
Let's say I have a go-app application already loaded and running in a browser / mobile device.  A new application version is deployed to the backend.

Being able to trigger service worker update ( without waiting on `AutoUpdateInterval` ) would be convenient. As @oderwat  mentioned, a websocket connection could signal that a new version is available and `app.RegistrationUpdate()` would force the service worker update outside of the normal interval.

Basically allowing a server push to signal that the go-app application should update the service worker.

**Comment by oderwat** [comment]
@maxence-charriere:

1. This was straight forward but there is a loophole with getting the current state and some browser support:

```go
	currentState = true // this is a guess
	// this may not be implemented
	nav := app.Window().Get("navigator")
	if nav.Truthy() {
		onLine := nav.Get("onLine")
		if !onLine.IsUndefined() {
			currentState = onLine.Bool()
			dbg.Logf("got state from navigator object")
		}
	}
	dbg.Logf("network state on init: %t", currentState)
	app.Window().Call("addEventListener", "online", app.FuncOf(func(this app.Value, args []app.Value) any {
		dbg.Log("network status: online")
		currentState = true
		call(true)
		return nil
	}))

	app.Window().Call("addEventListener", "offline", app.FuncOf(func(this app.Value, args []app.Value) any {
		dbg.Log("network status: offline")
		currentState = false
		call(false)
		return nil
	}))
```

2. I think @mlctrez and we have the same use case in mind. We can communicate with the frontend at will through NATS and so we would like to react quickly on problems with updates, especially when we do beta testing. We even can take screenshots and watch logdata from the PWA in realtime and have the code recompile with changes. In dev mode we run with 5 second checks for new updates, but you do not want to do that with multiple beta testers. So currently one needs to reload the app manually for getting to updates. We usually place some "click here to reload" functionality into the PWA like on the logo and then it will need multiple reloads till the app is updated. Sometimes people then reload while the server restarts and then hang in a half finished state and it is janky in general. That would be smoother if the server after restart and maybe microservice updates are finished, it just tells the apps that they should check for a new version.

3. So 'OnUpdate' is not called on updates but on external updates. I would like to have an "update" handler, that is called if the dom was changed. This is not dependent on the exported fields.

4. I think I may have described it wrong (or miss something). We want to call "ctx.Dispatch()" from a debouncer, the debouncer is getting a ctx (the go-app event handler that was triggered), this event then is prevented to update anything and does notthinb but to start/reset a timer. When this timer runs out it calls the "real" event handler. At that time the (last) event is processed by a method on the component. But this then does not receive a context, so it needs to have a copy of the original context to call "ctx.Dispatch()". or "ctx.Defer()". For the event debouncer we copy the last context and call the original go-app event handler with those. In other cases (nats consumer) we have another Go routine running that needs to create updates, so for this we copy the context we got at mounting into the component and use that for dispatching. This all works (TM) but it feels "cheating". Of course it would "crash" if there was a dismount but that can be handled if needed (stopping the timers / consumers, checking ctx != nil).

5. We use gob + compress + ascii85 to store data in indexdb. This makes it safe to decode (type check because of gob), easy to use (struct in / struct out) and is space efficient. I guess I thought that adding some generics based code may make it possible to make the code / ide using types for the data. For example we currently have a function that restores a bunch of [avrox](https://github.com/metatexx/avrox) encoded data (which is an extension to avro format that auto discoveres a schema in raw data) as a map of Nats subjects of some type. The function for this looks like `subjectMappedAcrox[avroxType]("subject.pattern")`. Which then resolves in the IDE and while compilation to `map[string]avroxType`. That makes it really nice to work with it. So I wondered if we could have something somilar for the states or action handlers. But this may be something that is to specialized for a general implementation in go-app.

6. Well, I would not call this a panic recovery if it calls `panic()` at the end :). What I mean with recovery is, that the app should not end up in an unresponsive state after a panic. It could call a callback that for example decides if the engine loop can continue/restart. It also could have the app display some custom information on what to do. I guess my main problem with a panic is, that it stops the reloading for an updated application, so a user that uses the app in a "kiosk" like situation, will never get a new version without manual reload the app, which is not possible through a gui element (because go app crashed) or the browser (there is no browser in kiosk mode). Think of a time recorder and people logging in and out and some error happens, the display is always on, the app is the ony thing that can run on the device. The users are not allowed to enter the system or have developer tools. They can only reboot the device and if the error happens again before the new software update is active, they have to reboot again.

**Comment by oderwat** [comment]
@astrolemonade The service worker is integral to this framework already. For push notifications see #725 (an the issue mentioned there)

**Comment by oderwat** [comment]
@maxence-charriere I checked the problem from #915 and v10 works for the way we use `ctx.PreventUpdate()`.

1. But I immediately run into the problem that @mlctrez mentioned: We use `c.Update()` quite a lot, because we have countless go routines running (for example NATS or something like an intersection handler). One concrete example is a counter component that is incremented even if not mounted and is called asynchronously.

```
type cCount struct {
	app.Compo
	count int
}

func (c *cCount) Render() app.UI {
	dbg.Logf("count: %d", c.count)
	return app.Div().Text(strconv.Itoa(c.count))
}

func (c *cCount) Set(count int) {
	if c.count != count {
		// only do something if needed
		c.count = count
		dbg.Logf("set to count: %d", c.count)
		// this prevents a panic if the counter is not mounted (because it may be displayed conditional)
		if c.Mounted() {
			// c.Update() // how to do that in v10?
		}
	}
}
```

2. Another thing is that we really need a way to force the service worker update as discussed by me and @mlctrez (https://github.com/maxence-charriere/go-app/issues/875#issuecomment-1811844839). In iOS we often do not have any update checks happen. So an update only works when force quitting the app. I think this may have to do with how frequent you check for updates but if you do not check it often you can't guarantee an update going through at all. And even if the backend tells the frontend that there is an update you can't "force quit" the application. I would love to not have to create another fork to build those things in and modifying the service worker through the template is a pain.

3. We also would really need a (optimized) way to call a function after the frame was rendered and before the next one is rendered. Something like that what I thought "OnUpdate()" would do. Having a callback for a component that only triggers if there were DOM nodes changed after Render() before anything else happens. We need this currently for space calculations where we need to know the dimensions and visibility state of elements on the page. Right now we need to "guess" if there were changes or just do our size caching "all the time". But that is a waste of CPU cycles that hurt the battery and performance on mobile. The use case is for example caching div heights for infinite scroller outside padding calculations or for adjusting the view when the layout needs to be changed because stuff gets to small/big. You can't handle everything using media based CSS.

**Comment by oderwat** [comment]
I found a way to implement this "counter". Is this how you would write something like that @maxence-charriere ?

```go
type cCount struct {
	app.Compo
	ctx   *app.Context
	count int
}

func (c *cCount) OnMount(ctx app.Context) {
	c.ctx = &ctx
}

func (c *cCount) Render() app.UI {
	dbg.Logf("count: %d", c.count)
	return app.Div().Text(strconv.Itoa(c.count))
}

func (c *cCount) Set(count int) {
	if c.count != count {
		// only do something if needed
		c.count = count
		dbg.Logf("set to count: %d", c.count)
		// this prevents a panic if the counter is not mounted (because it may be displayed conditional)
		if c.Mounted() && c.ctx != nil {
			c.ctx.Dispatch(func(context app.Context) {
				// nothing
			})
		}
	}
}
```

**Comment by oderwat** [comment]
An addition to the app updates: It seems that sometimes the `OnAppUpdate()` is not called.

Normally it looks like:

```
installing app worker 680968437690593471
wasm_exec.js:356 github.com/oderwat/picha/front.(*appControl).OnAppUpdate: there is an update
wasm_exec.js:356 127.0.0.1 has been updated, reload to see changes
app-worker.js:31 app worker 680968437690593471 is activated
Navigated to http://127.0.0.1:6969/
```

But then I get even:

```
installing app worker 680968437690593471
app-worker.js:31 app worker 680968437690593471 is activated
installing app worker 780968437690123431
app-worker.js:31 app worker 780968437690123431 is activated
```

Without any handler getting called. While the component is mounted and uses a very simple updater together with our watcher that recompiled automatically and checking for updates is set to 5 seconds.

```go
func (uc *appControl) OnAppUpdate(ctx app.Context) {
	if ctx.AppUpdateAvailable() {
		dbg.Logf("there is an update")
		ctx.Reload()
	}
}
```

**Comment by maxence-charriere** [comment]
> after the frame was rendered

What is the issue with `ctx.Defer`?


> func (c *cCount) Set(count int)

From where your Set is called?

**Comment by maxence-charriere** [comment]
> I found a way to implement this "counter". Is this how you would write something like that @maxence-charriere ?

can you give me the specs of your counter?

**Comment by oderwat** [comment]
The issue with defer is, that I think it is always called and not just when nodes where updated. We do not want to scan the DOM for layout changes if nothing has changed.

The issue with the counter is, that I am unsure if it is okay to store the context from OnMount and use it later like I do. It should not matter from where set is called. Thats the point of it. It could be called from a Go routine that is called by an intersection api handler or by a NATS consumer or even from OnRender().

@maxence-charriere I basically have the same question as the (unanswered) question from here: https://github.com/maxence-charriere/go-app/issues/875#issuecomment-1788119144

Why can't we just still have "c.Update()" in the API?

**Comment by oderwat** [comment]
Can we get some "Apply()" function, that can be used to add a function into something like this `app.Div().Apply(func(el any) any {return el.(HTMLDiv).Class("test")}).Text("foo")` ?

**Comment by maxence-charriere** [comment]
> Why can't we just still have "c.Update()" in the API?

Because that requires having cross-references between the engine and each component, which I try to avoid now.

>  I am unsure if it is okay to store the context from OnMount

It is okay, though might be better clean if the context contain an `Update()` function that you can store in a `field func()`

**Comment by maxence-charriere** [comment]
@oderwat OnUpdate is now triggered when a component is updated before its root is re-rendered. Not only when it is updated by the parent.
You can use Defer in OnUpdate if you need to adjust things after it is rendered.
Let me know how this plays.

**Comment by oderwat** [comment]
@maxence-charriere Firstly I want to thank you for your time (as I should do much more often)-

The `ctx.Update()` function works. Could you please explain why this is better than storing the context?

About `OnUpdate()` I can only say that this is now triggering always. What we need is a trigger if something was done in the DOM. To me, it looks like that there is nothing done, and it still `OnUpdate()` is getting called. For example, when I add a `OnClick()` handler that does absolutely nothing, OnUpdate() is being called. This could maybe be useful but is not what we need. We would still need to get all div's with a specific class to then check all of their heights every time any render event is triggered even if the display (DOM) is not getting changed at all.

P.S.: Besides that, we do not have any problems with the V10 "preview" yet. After another beta release tonight we plan to check with our largest app, if V10 is "good" for us and may even compile on the v10 commits for the next beta releases.

**Comment by maxence-charriere** [comment]
> The `ctx.Update()` function is operational. However, I'm curious about its advantages over direct context storage. Could you elaborate?

I came across a guideline on the [Go Developer Wiki](https://go.dev/wiki/CodeReviewComments#contexts) stating:

> "Avoid adding a `Context` member to a struct type. Prefer adding a `ctx` parameter to each method on that type that requires it. The exception is when matching the signature of an interface in the standard library or third-party libraries."

Admittedly, I don't always adhere strictly to these context recommendations 👎.

In the case of a go-app, a context can reference an element that might be unmounted. The `Update()` method incorporates safeguards to prevent actions if the associated element is invalid. Therefore, utilizing a function pointer in this context might be a safer and more robust approach.

**Comment by maxence-charriere** [comment]
@oderwat I also reverted the change that trigger OnUpdate for now. Not very satisfied with it.

**Comment by maxence-charriere** [comment]
> In reference to point "2" from my previous post: There are instances where `OnAppUpdate()` does not seem to be invoked.

This issue appears to be beyond the control of go-app and is more likely related to browser-specific behaviors or limitations.


```go
func (uc *appControl) OnAppUpdate(ctx app.Context) {
	if ctx.AppUpdateAvailable() {
		dbg.Logf("there is an update")
		ctx.Reload()
	}
}
```

`ctx.AppUpdateAvailable()` will always return false if the browser does not detect a change. However, if a change is detected, `OnAppUpdate` is triggered.

**Comment by maxence-charriere** [comment]
> The issue with defer is, that I think it is always called and not just when nodes where updated. We do not want to scan the DOM for layout changes if nothing has changed.

@oderwat I'm experimenting with something that addresses this in https://github.com/maxence-charriere/go-app/pull/921

**Comment by oderwat** [comment]
@maxence-charriere About the `ctx`: I think they mean, that you should not add the context to your receiver for a method but make it an argument, so it can be changed from call to call and method to method. I see your concern is mostly the unmount case, which we address in our code by checking `c.Mounted()` in relevant cases.

About the app updates: The cases we see (frequently) is where the service worker outputs it to the console (so it is noted by the browser) but it is not propagated to the app. At least this is how it looks. Besides, this I can only repeat: We need to trigger an update check "manually". Usage on different devices is showing that they do not updated reliably themselves. It looks like the OS tries to avoid update checks where it can. Please add something like that, so we do not need to replace the service worker with another version ourselves. We need to "kill" the apps to get updates working in many cases.

**Comment by maxence-charriere** [comment]
> Please add something like that, so we do not need to replace the service worker with another version ourselves.

@oderwat do you have a snippet about this?

**Comment by oderwat** [comment]
> > Please add something like that, so we do not need to replace the service worker with another version ourselves.
> 
> @oderwat do you have a snippet about this?

I wished we had. I started but stopped because I realized how hard it is to keep that parallel to your stuff. I think it should work by triggering the timer that waits. Maybe it could also be used to change the update check timing from the "front end"?

**Comment by maxence-charriere** [comment]
@oderwat , not yet what are you asking but could you check that notification issue with the latest v10.

**Comment by oderwat** [comment]
@maxence-charriere Will do, later tonight.

**Comment by oderwat** [comment]
@maxence-charriere I forgot something that may be easy for you to implement and would help to avoid a common error and 
 makes reusing components easier: It is about the problem I solved with the [mountpoint](https://github.com/metatexx/go-app-pkgs/tree/master/mountpoint). Please take a look and this example code: https://github.com/metatexx/go-app-pkgs/blob/master/examples/mountpoint/main.go

![mountpoint](https://github.com/maxence-charriere/go-app/assets/719156/d4cd6f79-5652-4989-9d9c-c9927f1857e5)

Basically I think I want to have a way to 'forcefully' dismount/mount a component with the same type when updating. It should be triggered when another instance of this same component go type is replacing the former one. I wonder how it could be implemented though. Maybe by adding a field to "app.Compo" that can be used to make different instances of the compo distinguishable for the updater? Something similar to the scope in the event handler.

The result should be, that I can implement the "tabs" from the example by using the 'intuitive' implementation of switching the app.UI by adding "something" to make that work.

**Comment by maxence-charriere** [comment]
@oderwat check https://github.com/maxence-charriere/go-app/pull/925

**Comment by oderwat** [comment]
@maxence-charriere I will check #925 later tonight. 

Right now I encountered another serious problem for us: It seems that "ctx.PreventUpdate()" does not "always" prevent updates of the parent component. In our full application a scroll event handler uses `ctx.PreventUpdate()` if a virtual window into the data does not need to be re-rendered. But even if I place `ctx.PreventDefault()` as the first and only line into the scroll handler, it still triggers an update of the parent component. This then causes it to update and `Render()` which then renders the child and therefor all the data will be rendered again and again.

Strangely enough, I can't reproduce it so far in test cases. Even with that same scroller component inside a stack of other components, I can't replicate that it triggers the update of its parent more than trice (see below). But there is something still strange: It renders it three times even if with 'prevent update' and then stops to render it. It also calls "render" when I just click "anywhere" in the page but only three times. And it does this in any browser: Opera, Firefox and Safari were tested to avoid interference with browser plugins. I am baffled.

Do you have an idea what may be the course of that or how we could try to debug this? As soon as I remove the event handler I do not get any updates when scrolling anymore. So it hast to be related to that event handler and that the prevention of the update is not working.

**Comment by maxence-charriere** [comment]
The update condition is now a counter so when you prevent an update, the counter decreases. My guess would be that the parent component update is triggered by something else.

**Comment by oderwat** [comment]
> The update condition is now a counter so when you prevent an update, the counter decreases. My guess would be that the parent component update is triggered by something else.

There are no other updates in my smallest testing app. It is quite basic and always updated three additional times, now I removed one of the hierarchies in the components and it then updates two additional times. What we found so far is, that the number of additional updates seems to depend on number and the depth of the component in the tree of the component root.

This almost looks like that the updates are kind of queued and hold back. This seems to happen when we call "ctx.Update()" and nothing happens "in the next frame" and these updates are delayed until another event handler triggers and then suddenly the updates happen. This seems to be the case with the "big" app I described first. There we found that the "update prevented" handler calls seem to "emptying" a "queue" of updates and after some time additional scroll events do stops updating the parent component. We can also use another event handler to clear updates (for example with click handlers) and after a while, no updates happen anymore. When we then scroll the handler also is not trigger updates anymore. So it seems that there is a side effect of "scrolling" events catching up with older update requests.

We also had occasions where our app was not updating the display at all just to update after we just click somewhere (trigger any event handler). Right now it looks like updates are pretty broken with v10 for our use cases. Can it be, that updates accumulate over multiple frames if there is no "other" event triggering an update in the "normal" way

**Comment by maxence-charriere** [comment]
@oderwat I issued some fixes concerning the component updates. Thanks for reporting this!

**Comment by oderwat** [comment]
> @oderwat I issued some fixes concerning the component updates. Thanks for reporting this!

@maxence-charriere We already checked it out, and it fixes the problems we had. Thank you for the fix!

**Comment by oderwat** [comment]
@maxence-charriere I think the storage interface is not a good design. We ran into problems because you can't check for "not found" and the input variable is not overwritten in that case.

<img width="382" alt="image" src="https://github.com/maxence-charriere/go-app/assets/719156/b32eee90-22de-4aa9-968f-9c374ee013a4">

I think that in the highlighted section some "not found" error should be returned.

**Comment by maxence-charriere** [comment]
`Key()` is to allow iterating into a js `localStorage` or `sessionStorage`
=> https://developer.mozilla.org/en-US/docs/Web/API/Storage/key

**Comment by oderwat** [comment]
> `Key()` is to allow iterating into a js `localStorage` or `sessionStorage`

They write the order is client dependent which (hopefully means) it is stable between calls. But your memory implementation is not stable as the map order is guaranteed to be stable between iterations (even if it often is).

And a `Keys()` function would go a long way too. Because using `for{}` with the `len()` and calling the `Key(index)` to get all the keys is ineffective and instable with the map implementation (at least).

> You can check not found with err == nil and if your receiver is the zero value

`nil` is also the return if it is found, and I can't (or want) to check for the zero value easily. Even if I do, I can't say if that value comes from the storage or is my current value. In addition, the receiver could also be initialized with something and can be (partially) overwritten as the result is unmarshalled over it. Which is an implementation detail but can bring challenges with updating structures and loading older data, which currently works.

I think you need to change this implementation to make it production ready.

**Comment by oderwat** [comment]
Where is `AddEventListener()` in v10? I just wanted to share some code with another of our project and found that this is gone. Why was this removed? We can use `app.Window().Call("addEventListener",...)` but I like it if it is abstracted.

**Comment by maxence-charriere** [comment]
@oderwat, I modified the `BrowserStorage` interface => https://github.com/maxence-charriere/go-app/pull/932

> Where is AddEventListener() in v10? I just wanted to share some code with another of our project and found that this is gone. Why was this removed? We can use app.Window().Call("addEventListener",...) but I like it if it is abstracted.

I removed it because it required to keep a reference to the engine as a global variable.

**Comment by oderwat** [comment]
> @oderwat, I modified the BrowserStorage interface => https://github.com/maxence-charriere/go-app/pull/932

Will check it out soon

> I removed it because it required to keep a reference to the engine as a global variable.

I just made something like this:

```go
func OnPaste(fn func(string)) func() {
	hFn := func(this app.Value, args []app.Value) any {
		event := args[0]
		clipboardData := event.Get("clipboardData")
		text := clipboardData.Call("getData", "text").String()
		fn(text)
		return nil
	}
	fo := app.FuncOf(hFn)
	app.Window().Call("addEventListener", "paste", fo)
	return fo.Release
}
```

Do you see a problem with that or may that inspire something you can build into Go-App?

**Comment by maxence-charriere** [comment]
> Do you see a problem with that or may that inspire something you can build into Go-App?

Previous implementation was using `Dispatch` to ensure that the call back runs on the UI grouting. I'm not sure about where JS callback are executed by default so all the go-app call are dispatched.

**Comment by maxence-charriere** [comment]
It seems it works but since I did not found an elegant way to include a dispatcher into the browser window and that the JS callback execution location is unclear to me, I removed the Helper.

**Comment by oderwat** [comment]
@maxence-charriere can you please consider adding the requested feature that we can signal the service worker to check for an update explicitly e.g. `app.TriggerUpdateCheck()`? This is currently our last wish for v10.

**Comment by maxence-charriere** [comment]
@oderwat in term of implementation, this is allowing to trigger `registration.update();` from app.js that is used for `Handler.AutoUpdateInterval`.

Feel like a duplicate here.
I rather try to figure out the issue with `Context.AppUpdateAvailable()` if you still have it.

**Comment by oderwat** [comment]
> @oderwat in term of implementation, this is allowing to trigger `registration.update();`

I can call `await goappServiceWorkerRegistration.update()` in the developer tools console to do what we need. But this is not possible from inside the app without implementing this as event on the service worker.

With such an event (+API call) in place we could set auto-update to a long time or even disable it and just use our steady NATS (WS) connection to signal the app(s) that there is an update available. This will let us get rid of the 5s polling for updates we use while development (for the auto-reloader) and also makes it more predictable when applications are checking for updates. We would also add that the user can check for an update. In addition, we could simply create our own interval bases checker that could have different patterns (using releases days, for example).

Adding the event to the service worker would go a long way and I do not see how this is a duplicate.

This change would not only make update checks more predictable but could also significantly reduce the load on our servers. Presently, the frequent polling system is largely ineffective, as updates are not needed 99.99% of the time, leading to unnecessary server demand. Having long times between checks makes it also hard in support situations. You can't have the user reload the application "to try for an update" as complex applications may lose their state.

Additionally, we can incorporate a feature that allows users to manually check for updates. This, coupled with our own interval-based update checker, would further enhance the update process. During development, the ability to update as soon as one is available is crucial. The proposed system would facilitate this, allowing server-side triggered updates that are currently not possible.

In summary, by adapting the service worker to include a specific update event, we can simplify the update process, reduce server strain, and provide a better experience for both developers and users.

**Comment by maxence-charriere** [comment]
This could be feasible but I feel i want to remove the auto update from handler. Does not make sense to have update checking to different location.

**Comment by oderwat** [comment]
> This could be feasible but I feel i want to remove the auto update from handler. Does not make sense to have update checking to different location.

We would be happy with that. I also think that having more control would make it more transparent for the developer what is actually happening. "Triggers and update check of the service-worker which makes a request to the server ..." or something similar. Removing it from the handler will also make people who use it aware of the changed API.

**Comment by oderwat** [comment]
@maxence-charriere I think we need a way to add the "purpose: maskable" to the icons objects in the webmanifest (see: https://developer.chrome.com/docs/lighthouse/pwa/maskable-icon-audit?hl=en)

**Comment by oderwat** [comment]
@maxence-charriere I tried using app notifications on a Samsung A9+ Tablet and got this (using our panic handler):

```
TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.
File: $GOROOT/src/syscall/js/js.go
Line: 397
```

Checking this further I found this:

> Chrome for Android will throw a TypeError when calling the Notification constructor. It only supports creating notifications from a service worker. See the Chromium issue tracker for more details. (from: https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification)

It seems, to be able to create notifications there also needs to be an event interface to the service worker for creating notifications. Is it feasible to add one?

**Comment by oderwat** [comment]
@maxence-charriere Your push event handler only expects JSON messages that are then used for notifications.

```
  const notification = JSON.parse(event.data.text());
  if (!notification) {
    return;
  }
```

But push messages are not bound to notifications. Many examples and even the debugging functions in chrome dev tools allow just any text (and afaik even up to 4096 bytes). Your current implementation panics in that case.

I think, we need `app.OnPushMessage(data string)` too. The current implementation does combine the web push with notifications. But they are different things. Currently, there is also no action at all performed if data is empty, but this should also result in some action. I think it should trigger `app.OnPushMessage("")`. Alternatively one could argue that it means to show a default notification, but I don't like that idea. 

As the push data is created by the same developer that creates the PWA, it could be safe to add extra fields to the data that lets us say if we want to have a notification displayed and probably also if the notification is also sent to the `OnPushMessage()`, so the PWAs do now that there was a notification sent that the user may have seen. So you could try/catch the json parsing (there is also data.json() btw) and if it is not JSON pass it to the PWA(s) `OnPushMessage` if it is json you could check for the field `notify` and if it is there and is 1 show the notification and if it is 2 you show + pass the data to `OnPushMessage`.

**Comment by oderwat** [comment]
@maxence-charriere Your even handlers are missing a way to set the passive option (see: https://dom.spec.whatwg.org/#dom-addeventlisteneroptions-passive). A god explanation of this topic is here: See https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

We get frequent warnings like this:

> wasm_exec.js:356 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

The apps work, but there may be performance improvements if supported and in addition: Each technically advanced person that can watch the console log, will have the impression that something is not right "because the devs where lazy".

I guess adding it will have quite the impact on your code. Maybe one could use a work-around by adding `On("touchstart:passive",...)` or anything ":passive" as name for the event and if that is detected you strip the suffix and add the option. This should be fairly easy to implement and solve the problem.

**Comment by maxence-charriere** [comment]
@oderwat just made a push on v10 branch => `ctx.TryUpdateApp()`

**Comment by mlctrez** [comment]
@maxence-charriere 

After replacing goappSetupAutoUpdate with goappTryUpdate , this line needs to be removed :

https://github.com/maxence-charriere/go-app/blob/cd97cdcb5008be6787bf88961ddb95709cc7fa0f/pkg/app/gen/app.js#L33

**Comment by maxence-charriere** [comment]
@mlctrez fixed

**Comment by maxence-charriere** [comment]
> I think we need a way to add the "purpose: maskable" to the icons objects in the webmanifes

@oderwat , replaced the apple touch icon with the maskable one.
=> https://github.com/maxence-charriere/go-app/pull/938

**Comment by maxence-charriere** [comment]
> your even handlers are missing a way to set the passive option 

@oderwat I made a PR for this: https://github.com/maxence-charriere/go-app/pull/942

Usage:
```go
// Event with scope
app.Div().OnScroll(func(cox app.Context, e app.Event){}, app.EventScope("1"))

// Passive event
app.Div().OnScroll(func(cox app.Context, e app.Event){}, app.PassiveEvent())

// Multiple options
app.Div().OnScroll(func(cox app.Context, e app.Event){},
    app.PassiveEvent(),
    app.EventScope("1"),
)
```

**Comment by oderwat** [comment]
@maxence-charriere this will need a lot of changes in our code and I do not like the idea to base multiple packages on a PR commit hash. I think it is a good way into the future to declare the event options using a concrete type. I would like that this is getting merged before we rewrite so much packages, just to rewrite them again, when it gets merged.

**Comment by oderwat** [comment]
Besides that I tested #942 in a smaller project, and it does what we need and is also fairly easy to updated and understand. I like that solution.

**Comment by oderwat** [comment]
BTW. I verified that "push notifications" (really "webpush") works with iOS 17.3.1 and the new (EU) 17.4 on the iPhone. I will test iPad later. It would be really cool if we could get the distinctions between "WebPush" and "Notifications" and implement a standard way for recognizing pushed notifications as I described above. See also #303 which was probably not seen by many people. @krustowski and I seem to have had the same journey to get it work.

**Comment by oderwat** [comment]
@maxence-charriere I wonder why `TryUpdateApp()` is on context. This makes using it problematic, because if you want to have the old timer based variant, it needs to be added inside a component. This seems unnecessary as it just uses app.Window() and can run anytime. I would suggest changing it to `app.TryUpdate()`.

**Comment by maxence-charriere** [comment]
> app.TryUpdate()

@oderwat Good idea, this has been modied

**Comment by maxence-charriere** [comment]
Do you folks use state broadcast?
Look like it prevent page caching and affect lighthouse performance test.

<img width="761" alt="Screenshot 2024-03-21 at 4 15 16 PM" src="https://github.com/maxence-charriere/go-app/assets/2692731/9f18b36a-0f91-4e7e-95ca-b481b36a847c">

Planning to either deprecate it or disable it by default.
What do you think?

**Comment by oderwat** [comment]
> Do you folks use state broadcast?

Not with our current apps. But we will most likely need inter tab communication (with local storage events or with event broadcast from the service worker) in the future. Our apps do not support forward/backward navigation anyway.

I think it would be okay, to have it implemented but disabled by default.

**Comment by oderwat** [comment]
@maxence-charriere another "thing"

We use "dark node" for some apps. So the default loading looks "wrong". I solve this by adding a raw header:

```Go
		RawHeaders: []string{`<style>
    .goapp-app-info {
        background-color: #000 !important;
        color: white !important;
    }
</style>`},
```

I think this should be configurable in `app.Handler`. Is that feasible?

**Comment by oderwat** [comment]
> you should be able to solve that with any css.

Not just "any". I believe it has to be embedded in the page and use "!important", so it overrides your hard coded media query `app.css` styles. I just wonder if `app.css` really needs to be hard coded and added instead of being created when the server starts, so that the content can be modified in an easier way. For example: Not every app wants to support different color schemes and your standard code uses the scheme with the media query while loading. I am not even sure, if we can override a media query based CSS with the `!important`, if our light scheme would have another background. This may end in the requirement to write a http-handler to catch "app.css" requests to replace them with something else (we did something like this with the manifest too in the past).

**Comment by maxence-charriere** [comment]
this is how I made it on Murlok.io:

```css
.goapp-app-info {
  color: var(--text-color);
  background: var(--default-background);
}
```

Does not seems to be !important

**Comment by oderwat** [comment]
@maxence-charriere Yes. It works as you say. I think there is this stupid bug(?) with Safari, that does not update the CSS used for the display when the app gets an update that changes CSS. It loads the new app but uses the former CSS. You need to hard kill the application and start it again. This is partly reproducible in Safari in OSX. I think that this was the problem we had, why it was not working the "easy" way when we tried this months ago.

**Comment by oderwat** [comment]
@maxence-charriere I think that we also need `app.EventNotPassive()` setting the option to 'false', to suppress warnings with such handlers that actually want to use prevent Default (we use both). So this either needs to be added or the former one needs to get a bool argument.

**Comment by maxence-charriere** [comment]
I don’t understand the need since it is non passive by default. Since you should not call prevent default with the passive option, a same handler should not be used for passive and non passive.

**Comment by oderwat** [comment]
> I don’t understand the need since it is non passive by default

Do you specify `{ passive: false }` as default? If not, this seems to be what Chrome checks for to not show the debug message if you use prevent Default in such a handler.

**Comment by maxence-charriere** [comment]
@oderwat from what I read,
Prevent default should not be called when an event handler is set to passive.

when there is no passive option, no passive field is set so the default value is whatever the browser set (which should be false).

Chrome seems to be unhappy if you set a non passive handler with `wheel`, or if you call prevent default in a passive handler.

I think that issue should be handled in your code by making sure to not use prevent default in a passive handler.

**Comment by oderwat** [comment]
@maxence-charriere I think that there was something changed in Chrome which makes this obsolete. It all works for us without the problem that was mentioned in that StackOverflow article. I forgot to update / remove that request.

**Comment by maxence-charriere** [comment]
@oderwat, I noticed that on Murlok.io as well. I haven't changed anything, but I observed it occurs when the ads fail to load some elements.

Do you see any errors or warnings in the browser console?

**Comment by maxence-charriere** [comment]
@oderwat, I've just implemented a fix that addresses the issue of the service worker being activated before the WASM is loaded. Please let me know if this resolves the problem.

**Comment by oderwat** [comment]
@maxence-charriere I had some time to check the fix with different projects and "updater" setups, and it seems to solve the problems we saw before. Thank you!

**Comment by maxence-charriere** [comment]
I'm planning to move forward and release version 10. This release is long overdue! 😀

A quick note on push notifications: I attempted to migrate them to the service worker, but unfortunately, I wasn’t successful.

If there's anything specific you think needs to be addressed before the v10 release, please let me know.

**Comment by maxence-charriere** [comment]
https://github.com/maxence-charriere/go-app/releases/tag/v10.0.0

**Comment by gepengscu** [comment]
why private app.Value addEventListener method ?

**Comment by maxence-charriere** [comment]
@gepengscu A javascript value is not necessary a DOM element.
